[package]
name = "rust_sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
rustyline = "17.0.2"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.149"
sqlparser = "0.60.0"
thiserror = "2.0.17"
