[package]
name = "rust_sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
rustyline = "17.0.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
serde_json = "1.0.149"
sqlparser = "0.39.0"
thiserror = "2.0.17"
